import { contextBridge, ipcRenderer } from "electron";
import { IPC, type ElectronAPI } from "../shared/ipc";

const api: ElectronAPI = {
  ping: () => ipcRenderer.invoke(IPC.PING),
  getAppInfo: () => ipcRenderer.invoke(IPC.GET_APP_INFO),
  login: (username, password) => ipcRenderer.invoke(IPC.AUTH_LOGIN, username, password),
  logout: () => ipcRenderer.invoke(IPC.AUTH_LOGOUT),
  getCurrentUser: () => ipcRenderer.invoke(IPC.AUTH_CURRENT_USER),
  changePassword: (currentPassword, newPassword) =>
    ipcRenderer.invoke(IPC.AUTH_CHANGE_PASSWORD, currentPassword, newPassword),
  vendorUnlock: (code) => ipcRenderer.invoke(IPC.AUTH_VENDOR_UNLOCK, code),
  getDbStats: () => ipcRenderer.invoke(IPC.DB_STATS),

  nextDocumentNumber: (docType) => ipcRenderer.invoke(IPC.DOCS_NEXT_NUMBER, docType),

  listUnits: () => ipcRenderer.invoke(IPC.UNITS_LIST),
  createUnit: (input) => ipcRenderer.invoke(IPC.UNITS_CREATE, input),
  updateUnit: (id, input) => ipcRenderer.invoke(IPC.UNITS_UPDATE, id, input),
  deleteUnit: (id) => ipcRenderer.invoke(IPC.UNITS_DELETE, id),

  listCategories: () => ipcRenderer.invoke(IPC.CATEGORIES_LIST),
  createCategory: (input) => ipcRenderer.invoke(IPC.CATEGORIES_CREATE, input),
  updateCategory: (id, input) => ipcRenderer.invoke(IPC.CATEGORIES_UPDATE, id, input),
  deleteCategory: (id) => ipcRenderer.invoke(IPC.CATEGORIES_DELETE, id),

  listTaxes: () => ipcRenderer.invoke(IPC.TAXES_LIST),
  createTax: (input) => ipcRenderer.invoke(IPC.TAXES_CREATE, input),
  updateTax: (id, input) => ipcRenderer.invoke(IPC.TAXES_UPDATE, id, input),
  deleteTax: (id) => ipcRenderer.invoke(IPC.TAXES_DELETE, id),

  listDiscounts: () => ipcRenderer.invoke(IPC.DISCOUNTS_LIST),
  createDiscount: (input) => ipcRenderer.invoke(IPC.DISCOUNTS_CREATE, input),
  updateDiscount: (id, input) => ipcRenderer.invoke(IPC.DISCOUNTS_UPDATE, id, input),
  deleteDiscount: (id) => ipcRenderer.invoke(IPC.DISCOUNTS_DELETE, id),

  listAdditions: () => ipcRenderer.invoke(IPC.ADDITIONS_LIST),
  createAddition: (input) => ipcRenderer.invoke(IPC.ADDITIONS_CREATE, input),
  updateAddition: (id, input) => ipcRenderer.invoke(IPC.ADDITIONS_UPDATE, id, input),
  deleteAddition: (id) => ipcRenderer.invoke(IPC.ADDITIONS_DELETE, id),

  listProducts: () => ipcRenderer.invoke(IPC.PRODUCTS_LIST),
  getProduct: (id) => ipcRenderer.invoke(IPC.PRODUCTS_GET, id),
  createProduct: (input) => ipcRenderer.invoke(IPC.PRODUCTS_CREATE, input),
  updateProduct: (id, input) => ipcRenderer.invoke(IPC.PRODUCTS_UPDATE, id, input),
  deleteProduct: (id) => ipcRenderer.invoke(IPC.PRODUCTS_DELETE, id),

  listVariants: (productId) => ipcRenderer.invoke(IPC.VARIANTS_LIST, productId),
  createVariant: (productId, input) => ipcRenderer.invoke(IPC.VARIANTS_CREATE, productId, input),
  updateVariant: (id, input) => ipcRenderer.invoke(IPC.VARIANTS_UPDATE, id, input),
  deleteVariant: (id) => ipcRenderer.invoke(IPC.VARIANTS_DELETE, id),

  listInventory: () => ipcRenderer.invoke(IPC.INVENTORY_LIST),
  adjustStock: (input) => ipcRenderer.invoke(IPC.INVENTORY_ADJUST, input),
  listCustomers: () => ipcRenderer.invoke(IPC.CUSTOMERS_LIST),
  createCustomer: (input) => ipcRenderer.invoke(IPC.CUSTOMERS_CREATE, input),
  updateCustomer: (id, input) => ipcRenderer.invoke(IPC.CUSTOMERS_UPDATE, id, input),
  deleteCustomer: (id) => ipcRenderer.invoke(IPC.CUSTOMERS_DELETE, id),

  listVendors: () => ipcRenderer.invoke(IPC.VENDORS_LIST),
  createVendor: (input) => ipcRenderer.invoke(IPC.VENDORS_CREATE, input),
  updateVendor: (id, input) => ipcRenderer.invoke(IPC.VENDORS_UPDATE, id, input),
  deleteVendor: (id) => ipcRenderer.invoke(IPC.VENDORS_DELETE, id),

  listAccounts: (filter) => ipcRenderer.invoke(IPC.ACCOUNTS_LIST, filter),
  getAccount: (id) => ipcRenderer.invoke(IPC.ACCOUNTS_GET, id),
  setCashBankOpenings: (input) => ipcRenderer.invoke(IPC.ACCOUNTS_SET_CASH_BANK_OPENING, input),
  postVoucher: (input) => ipcRenderer.invoke(IPC.VOUCHERS_POST, input),
  updateVoucher: (id, input) => ipcRenderer.invoke(IPC.VOUCHERS_UPDATE, id, input),
  getVoucher: (id) => ipcRenderer.invoke(IPC.VOUCHERS_GET, id),
  listVouchers: (filter) => ipcRenderer.invoke(IPC.VOUCHERS_LIST, filter),
  cancelVoucher: (id) => ipcRenderer.invoke(IPC.VOUCHERS_CANCEL, id),
  getAccountLedger: (accountId, query) => ipcRenderer.invoke(IPC.LEDGER_ACCOUNT, accountId, query),
  getPartyLedger: (partyType, partyId, query) =>
    ipcRenderer.invoke(IPC.LEDGER_PARTY, partyType, partyId, query),

  receivePayment: (input) => ipcRenderer.invoke(IPC.TX_RECEIVE, input),
  updateReceivePayment: (id, input) => ipcRenderer.invoke(IPC.TX_RECEIVE_UPDATE, id, input),
  makePayment: (input) => ipcRenderer.invoke(IPC.TX_PAY, input),
  updateMakePayment: (id, input) => ipcRenderer.invoke(IPC.TX_PAY_UPDATE, id, input),
  postExpense: (input) => ipcRenderer.invoke(IPC.TX_EXPENSE, input),
  updateExpense: (id, input) => ipcRenderer.invoke(IPC.TX_EXPENSE_UPDATE, id, input),
  postIncome: (input) => ipcRenderer.invoke(IPC.TX_INCOME, input),
  updateIncome: (id, input) => ipcRenderer.invoke(IPC.TX_INCOME_UPDATE, id, input),
  postOwnerDraw: (input) => ipcRenderer.invoke(IPC.TX_OWNER_DRAW, input),
  updateOwnerDraw: (id, input) => ipcRenderer.invoke(IPC.TX_OWNER_DRAW_UPDATE, id, input),

  listPurchases: () => ipcRenderer.invoke(IPC.PURCHASES_LIST),
  getPurchase: (id) => ipcRenderer.invoke(IPC.PURCHASES_GET, id),
  listPurchasesByVendor: (vendorId) => ipcRenderer.invoke(IPC.PURCHASES_LIST_BY_VENDOR, vendorId),
  createPurchase: (input) => ipcRenderer.invoke(IPC.PURCHASES_CREATE, input),
  updatePurchase: (id, input) => ipcRenderer.invoke(IPC.PURCHASES_UPDATE, id, input),
  deletePurchase: (id) => ipcRenderer.invoke(IPC.PURCHASES_DELETE, id),
  listPurchaseReturns: () => ipcRenderer.invoke(IPC.PURCHASE_RETURNS_LIST),
  getPurchaseReturn: (id) => ipcRenderer.invoke(IPC.PURCHASE_RETURNS_GET, id),
  createPurchaseReturn: (input) => ipcRenderer.invoke(IPC.PURCHASE_RETURNS_CREATE, input),

  listSales: () => ipcRenderer.invoke(IPC.SALES_LIST),
  getSale: (id) => ipcRenderer.invoke(IPC.SALES_GET, id),
  listSalesByCustomer: (customerId) => ipcRenderer.invoke(IPC.SALES_LIST_BY_CUSTOMER, customerId),
  createSale: (input) => ipcRenderer.invoke(IPC.SALES_CREATE, input),
  updateSale: (id, input) => ipcRenderer.invoke(IPC.SALES_UPDATE, id, input),
  deleteSale: (id) => ipcRenderer.invoke(IPC.SALES_DELETE, id),
  listSaleReturns: () => ipcRenderer.invoke(IPC.SALE_RETURNS_LIST),
  getSaleReturn: (id) => ipcRenderer.invoke(IPC.SALE_RETURNS_GET, id),
  createSaleReturn: (input) => ipcRenderer.invoke(IPC.SALE_RETURNS_CREATE, input),

  getDashboardSummary: () => ipcRenderer.invoke(IPC.DASHBOARD_SUMMARY),
  getSalesReport: (query) => ipcRenderer.invoke(IPC.REPORTS_SALES, query),
  getPurchasesReport: (query) => ipcRenderer.invoke(IPC.REPORTS_PURCHASES, query),
  getProfitReport: (query) => ipcRenderer.invoke(IPC.REPORTS_PROFIT, query),
  getStockReport: () => ipcRenderer.invoke(IPC.REPORTS_STOCK),
  getTaxReport: (query) => ipcRenderer.invoke(IPC.REPORTS_TAX),
  getDeletedDocumentsReport: (query) => ipcRenderer.invoke(IPC.REPORTS_DELETED, query),

  listClientCompanies: () => ipcRenderer.invoke(IPC.COMPANIES_LIST),
  createClientCompany: (input) => ipcRenderer.invoke(IPC.COMPANIES_CREATE, input),
  updateClientCompany: (id, input) => ipcRenderer.invoke(IPC.COMPANIES_UPDATE, id, input),
  deleteClientCompany: (id) => ipcRenderer.invoke(IPC.COMPANIES_DELETE, id),
  getCompaniesDemand: () => ipcRenderer.invoke(IPC.COMPANIES_DEMAND),

  getSettings: () => ipcRenderer.invoke(IPC.SETTINGS_GET_ALL),
  updateSettings: (input) => ipcRenderer.invoke(IPC.SETTINGS_UPDATE, input),
  setShopLogo: (dataUrl) => ipcRenderer.invoke(IPC.SETTINGS_SET_LOGO, dataUrl),
  clearShopLogo: () => ipcRenderer.invoke(IPC.SETTINGS_CLEAR_LOGO),
  listUsers: () => ipcRenderer.invoke(IPC.USERS_LIST),
  createUser: (input) => ipcRenderer.invoke(IPC.USERS_CREATE, input),
  updateUser: (id, input) => ipcRenderer.invoke(IPC.USERS_UPDATE, id, input),
  setUserPassword: (id, password) => ipcRenderer.invoke(IPC.USERS_SET_PASSWORD, id, password),
  listRoles: () => ipcRenderer.invoke(IPC.ROLES_LIST),
  listPermissions: () => ipcRenderer.invoke(IPC.PERMISSIONS_LIST),
  setRolePermissions: (roleId, permissionCodes) =>
    ipcRenderer.invoke(IPC.ROLES_SET_PERMISSIONS, roleId, permissionCodes),
  listAuditLogs: (query) => ipcRenderer.invoke(IPC.AUDIT_LIST, query),
  printHtml: (html) => ipcRenderer.invoke(IPC.APP_PRINT_HTML, html),
  receiptImage: (input) => ipcRenderer.invoke(IPC.APP_RECEIPT_IMAGE, input),
  saveFile: (input) => ipcRenderer.invoke(IPC.APP_SAVE_FILE, input),

  getBackupStatus: () => ipcRenderer.invoke(IPC.BACKUP_STATUS),
  runManualBackup: () => ipcRenderer.invoke(IPC.BACKUP_RUN_MANUAL),
  runAutoBackupNow: () => ipcRenderer.invoke(IPC.BACKUP_RUN_AUTO),
  restoreBackup: (sourcePath) => ipcRenderer.invoke(IPC.BACKUP_RESTORE, sourcePath),
  pickBackupFile: () => ipcRenderer.invoke(IPC.BACKUP_PICK_FILE),
  openBackupFolder: () => ipcRenderer.invoke(IPC.BACKUP_OPEN_FOLDER),
  resetShopData: (confirmText) => ipcRenderer.invoke(IPC.BACKUP_RESET_SHOP, confirmText),

  getLicenseStatus: () => ipcRenderer.invoke(IPC.LICENSE_STATUS),
  listLicenses: () => ipcRenderer.invoke(IPC.LICENSE_LIST),
  createLicense: (input) => ipcRenderer.invoke(IPC.LICENSE_CREATE, input),
  deleteLicense: (id) => ipcRenderer.invoke(IPC.LICENSE_DELETE, id),
  expireTrialForTesting: () => ipcRenderer.invoke(IPC.LICENSE_EXPIRE_TRIAL),
  lockThisInstallNow: () => ipcRenderer.invoke(IPC.LICENSE_LOCK_NOW),
  applyActivationCode: (code) => ipcRenderer.invoke(IPC.LICENSE_APPLY_CODE, code),

  getN8nStatus: () => ipcRenderer.invoke(IPC.N8N_STATUS),
  flushN8nQueue: () => ipcRenderer.invoke(IPC.N8N_FLUSH),
  testN8nWebhook: (to) => ipcRenderer.invoke(IPC.N8N_TEST, to),

  getCloudSyncStatus: () => ipcRenderer.invoke(IPC.CLOUD_SYNC_STATUS),
  runCloudSyncNow: () => ipcRenderer.invoke(IPC.CLOUD_SYNC_NOW),
};

contextBridge.exposeInMainWorld("api", api);
